In [1]:
import genesis as gs
import numpy as np

[I 03/13/25 14:59:10.946 82664] [shell.py:_shell_pop_print@23] Graphical python shell detected, using wrapped sys.stdout


In [2]:
gs.init(backend=gs.cpu)

[Genesis] [14:59:42] [INFO] ╭───────────────────────────────────────────────╮
[Genesis] [14:59:42] [INFO] │┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈ Genesis ┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈│
[Genesis] [14:59:42] [INFO] ╰───────────────────────────────────────────────╯
[Genesis] [14:59:42] [INFO] Running on [11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz] with backend gs.cpu. Device memory: 62.64 GB.
[Genesis] [14:59:43] [INFO] 🚀 Genesis initialized. 🔖 version: 0.2.1, 🌱 seed: None, 📏 precision: '32', 🐛 debug: False, 🎨 theme: 'dark'.


In [3]:
scene = gs.Scene(
    show_viewer = True,
    # this is the viewer window that opens while the simulation is running, rather than the camera that records the video
    viewer_options = gs.options.ViewerOptions(
        res           = (1280, 960),
        camera_pos    = (3.5, 0.0, 2.5),
        camera_lookat = (0.0, 0.0, 0.5),
        camera_fov    = 30,
        max_FPS       = 60,
    ),
    vis_options = gs.options.VisOptions(
        show_world_frame = True,
        world_frame_size = 1.0,
        show_link_frame  = False,
        show_cameras     = False,
        plane_reflection = True,
        ambient_light    = (0.1, 0.1, 0.1),
    ),
        sim_options = gs.options.SimOptions(
        dt = 0.01,
        substeps = 4,
    ),
    renderer=gs.renderers.Rasterizer(),
)

[Genesis] [14:59:45] [INFO] Scene <58784d6> created.


In [4]:
plane = scene.add_entity(
    gs.morphs.Plane(),
)
panda = scene.add_entity(
    gs.morphs.MJCF(file='../genesis/mujoco_menagerie/franka_emika_panda/panda.xml'),
)
box = scene.add_entity(
    gs.morphs.Box(
        size=(0.05, 0.05, 0.05),
        pos=(0.65, 0, 0.25),
    ),
    surface=gs.surfaces.Default(
        color=(1, 0.8, 0),
    )
)

[Genesis] [14:59:47] [INFO] Adding <gs.RigidEntity>. idx: 0, uid: <f20a6ba>, morph: <gs.morphs.Plane>, material: <gs.materials.Rigid>.
[Genesis] [14:59:47] [INFO] Adding <gs.RigidEntity>. idx: 1, uid: <ac38d58>, morph: <gs.morphs.MJCF(file='/home/a3r/Interns/internship2024-25/genesis/mujoco_menagerie/franka_emika_panda/panda.xml')>, material: <gs.materials.Rigid>.
[Genesis] [14:59:49] [INFO] Adding <gs.RigidEntity>. idx: 2, uid: <0fd97e9>, morph: <gs.morphs.Box>, material: <gs.materials.Rigid>.


In [5]:
cam = scene.add_camera(
    res    = (640, 480),
    pos    = (1.25, -2.5, 1.3),
    lookat = (0.65, 0, 0.25),
    fov    = 20,
    GUI    = True,
)

In [6]:
scene.build()

[Genesis] [14:59:53] [INFO] Building scene <58784d6>...
[W 03/13/25 14:59:54.574 82664] [frontend_ir.cpp:begin_frontend_struct_for_on_snode@1678] ti.loop_config(serialize=True) does not have effect on the struct for. The execution order is not guaranteed.
[W 03/13/25 14:59:54.940 82664] [frontend_ir.cpp:begin_frontend_struct_for_on_snode@1678] ti.loop_config(serialize=True) does not have effect on the struct for. The execution order is not guaranteed.
[W 03/13/25 14:59:57.016 82664] [frontend_ir.cpp:begin_frontend_struct_for_on_snode@1678] ti.loop_config(serialize=True) does not have effect on the struct for. The execution order is not guaranteed.
[Genesis] [14:59:57] [INFO] Compiling simulation kernels...
[Genesis] [15:00:00] [INFO] Building visualizer...
[Genesis] [15:00:04] [INFO] Viewer created. Resolution: 1280×960, max_FPS: 60.


In [7]:
cam.render()

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is n

(array([[[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        [[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        [[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        ...,
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 63],
         [30, 46, 63],
         [30, 46, 63]],
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 63],
         [30, 46, 63],
         [30, 46, 63]],
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 62],
         [30, 46, 63],
         [30, 46, 63]]], dtype=uint8),
 None,
 None,
 None)

In [8]:
motors_dof = np.arange(7)
fingers_dof = np.arange(7,9)


panda.set_dofs_kp(
    np.array([4500, 4500, 3500, 3500, 2000, 2000, 2000, 100, 100]),
)
panda.set_dofs_kv(
    np.array([450, 450, 350, 350, 200, 200, 200, 10, 10]),
)
panda.set_dofs_force_range(
    np.array([-87, -87, -87, -87, -12, -12, -12, -100, -100]),
    np.array([87, 87, 87, 87, 12, 12, 12, 100, 100]),
)

# get the end-effector link
end_effector = panda.get_link('hand')

import time

# starting position
qpos = panda.inverse_kinematics(
    link = end_effector,
    pos = np.array([0.65, 0.5, 0.25]),
    quat = np.array([0, 1, 0, 0]),
)

In [9]:
scene.step()

[Genesis] [15:00:34] [INFO] Running at 0.67 FPS.


In [10]:
cam.render()

(array([[[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        [[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        [[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        ...,
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 63],
         [30, 46, 63],
         [30, 46, 63]],
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 63],
         [30, 46, 63],
         [30, 46, 63]],
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 62],
         [30, 46, 63],
         [30, 46, 63]]], dtype=uint8),
 None,
 None,
 None)

In [11]:
panda.control_dofs_position(qpos[:-2], motors_dof)
for i in range(100):
    scene.step()
    cam.render()

[Genesis] [15:00:48] [INFO] Running at 0.47 FPS.
[Genesis] [15:00:48] [INFO] Running at 0.50 FPS.
[Genesis] [15:00:48] [INFO] Running at 0.52 FPS.
[Genesis] [15:00:48] [INFO] Running at 0.55 FPS.
[Genesis] [15:00:48] [INFO] Running at 0.58 FPS.
[Genesis] [15:00:48] [INFO] Running at 0.61 FPS.
[Genesis] [15:00:48] [INFO] Running at 0.64 FPS.
[Genesis] [15:00:48] [INFO] Running at 0.67 FPS.
[Genesis] [15:00:48] [INFO] Running at 0.71 FPS.
[Genesis] [15:00:48] [INFO] Running at 0.75 FPS.
[Genesis] [15:00:48] [INFO] Running at 0.78 FPS.
[Genesis] [15:00:49] [INFO] Running at 0.82 FPS.
[Genesis] [15:00:49] [INFO] Running at 0.87 FPS.
[Genesis] [15:00:49] [INFO] Running at 0.91 FPS.
[Genesis] [15:00:49] [INFO] Running at 0.96 FPS.
[Genesis] [15:00:49] [INFO] Running at 1.01 FPS.
[Genesis] [15:00:49] [INFO] Running at 1.06 FPS.
[Genesis] [15:00:49] [INFO] Running at 1.11 FPS.
[Genesis] [15:00:49] [INFO] Running at 1.17 FPS.
[Genesis] [15:00:49] [INFO] Running at 1.23 FPS.
[Genesis] [15:00:49]

In [12]:
cam.set_pose(pos=(0.1, 0.2, 0.2), lookat=(0.65, 0.15, 0))
cam.set_params(fov=70)

cam.render()

(array([[[ 90,  90,  90],
         [ 90,  90,  90],
         [ 90,  90,  90],
         ...,
         [ 10,  20,  31],
         [ 10,  20,  31],
         [ 10,  20,  31]],
 
        [[ 90,  90,  90],
         [ 90,  90,  90],
         [ 90,  90,  90],
         ...,
         [ 10,  20,  31],
         [ 10,  20,  31],
         [ 10,  20,  31]],
 
        [[ 90,  90,  90],
         [ 90,  90,  90],
         [ 90,  90,  90],
         ...,
         [ 10,  20,  31],
         [ 10,  20,  31],
         [ 10,  20,  31]],
 
        ...,
 
        [[ 49,  66,  86],
         [ 49,  66,  86],
         [ 49,  66,  86],
         ...,
         [190,  48,  48],
         [192,  50,  50],
         [193,  51,  51]],
 
        [[ 49,  66,  86],
         [ 49,  66,  86],
         [ 49,  66,  86],
         ...,
         [187,  46,  46],
         [190,  48,  48],
         [192,  50,  50]],
 
        [[ 49,  66,  86],
         [ 49,  66,  86],
         [ 49,  66,  86],
         ...,
         [183,  44,  44],
  

In [13]:
for i in range(100):
    scene.step()
    cam.render()

[Genesis] [15:03:34] [INFO] Running at 0.12 FPS.
QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObject::moveToThread: Current thread (0x517262c0) is not the object's thread (0x55151ba0).
Cannot move to target thread (0x517262c0)

QObjec

: 