In [2]:
import genesis as gs
import numpy as np

In [3]:
gs.init(backend=gs.cpu)

[Genesis] [12:50:40] [INFO] ╭───────────────────────────────────────────────╮
[Genesis] [12:50:40] [INFO] │┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈ Genesis ┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈│
[Genesis] [12:50:40] [INFO] ╰───────────────────────────────────────────────╯
[Genesis] [12:50:40] [INFO] Running on [11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz] with backend gs.cpu. Device memory: 62.64 GB.
[Genesis] [12:50:40] [INFO] 🚀 Genesis initialized. 🔖 version: 0.2.1, 🌱 seed: None, 📏 precision: '32', 🐛 debug: False, 🎨 theme: 'dark'.


In [4]:
scene = gs.Scene(
    show_viewer = True,
    # this is the viewer window that opens while the simulation is running, rather than the camera that records the video
    viewer_options = gs.options.ViewerOptions(
        res           = (1280, 960),
        camera_pos    = (3.5, 0.0, 2.5),
        camera_lookat = (0.0, 0.0, 0.5),
        camera_fov    = 30,
        max_FPS       = 60,
    ),
    vis_options = gs.options.VisOptions(
        show_world_frame = True,
        world_frame_size = 1.0,
        show_link_frame  = False,
        show_cameras     = False,
        plane_reflection = True,
        ambient_light    = (0.1, 0.1, 0.1),
    ),
        sim_options = gs.options.SimOptions(
        dt = 0.01,
        substeps = 4,
    ),
    renderer=gs.renderers.Rasterizer(),
)

[Genesis] [12:50:41] [INFO] Scene <aa3d4e1> created.


In [5]:
plane = scene.add_entity(
    gs.morphs.Plane(),
)
panda = scene.add_entity(
    gs.morphs.MJCF(file='../genesis/mujoco_menagerie/franka_emika_panda/panda.xml'),
)
box = scene.add_entity(
    gs.morphs.Box(
        size=(0.05, 0.05, 0.05),
        pos=(0.65, 0, 0.25),
    ),
    surface=gs.surfaces.Default(
        color=(1, 0.8, 0),
    )
)

[Genesis] [12:50:42] [INFO] Adding <gs.RigidEntity>. idx: 0, uid: <4a8e054>, morph: <gs.morphs.Plane>, material: <gs.materials.Rigid>.
[Genesis] [12:50:42] [INFO] Adding <gs.RigidEntity>. idx: 1, uid: <9d24eb5>, morph: <gs.morphs.MJCF(file='/home/a3r/Interns/internship2024-25/genesis/mujoco_menagerie/franka_emika_panda/panda.xml')>, material: <gs.materials.Rigid>.
[Genesis] [12:50:42] [INFO] Adding <gs.RigidEntity>. idx: 2, uid: <686f03f>, morph: <gs.morphs.Box>, material: <gs.materials.Rigid>.


In [6]:
cam = scene.add_camera(
    res    = (640, 480),
    pos    = (1.25, -2.5, 1.3),
    lookat = (0.65, 0, 0.25),
    fov    = 20,
    GUI    = True,
)

In [7]:
scene.build()

[Genesis] [12:50:44] [INFO] Building scene <aa3d4e1>...
[W 02/27/25 12:50:44.906 75940] [frontend_ir.cpp:begin_frontend_struct_for_on_snode@1678] ti.loop_config(serialize=True) does not have effect on the struct for. The execution order is not guaranteed.
[W 02/27/25 12:50:45.146 75940] [frontend_ir.cpp:begin_frontend_struct_for_on_snode@1678] ti.loop_config(serialize=True) does not have effect on the struct for. The execution order is not guaranteed.
[W 02/27/25 12:50:46.920 75940] [frontend_ir.cpp:begin_frontend_struct_for_on_snode@1678] ti.loop_config(serialize=True) does not have effect on the struct for. The execution order is not guaranteed.
[Genesis] [12:50:46] [INFO] Compiling simulation kernels...
[Genesis] [12:50:50] [INFO] Building visualizer...
[Genesis] [12:50:50] [INFO] Viewer created. Resolution: 1280×960, max_FPS: 60.


In [8]:
cam.render()

QObject::moveToThread: Current thread (0x2a84dc60) is not the object's thread (0x2ee753b0).
Cannot move to target thread (0x2a84dc60)

QObject::moveToThread: Current thread (0x2a84dc60) is not the object's thread (0x2ee753b0).
Cannot move to target thread (0x2a84dc60)

QObject::moveToThread: Current thread (0x2a84dc60) is not the object's thread (0x2ee753b0).
Cannot move to target thread (0x2a84dc60)

QObject::moveToThread: Current thread (0x2a84dc60) is not the object's thread (0x2ee753b0).
Cannot move to target thread (0x2a84dc60)

QObject::moveToThread: Current thread (0x2a84dc60) is not the object's thread (0x2ee753b0).
Cannot move to target thread (0x2a84dc60)

QObject::moveToThread: Current thread (0x2a84dc60) is not the object's thread (0x2ee753b0).
Cannot move to target thread (0x2a84dc60)

QObject::moveToThread: Current thread (0x2a84dc60) is not the object's thread (0x2ee753b0).
Cannot move to target thread (0x2a84dc60)

QObject::moveToThread: Current thread (0x2a84dc60) is n

(array([[[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        [[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        [[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        ...,
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 63],
         [30, 46, 63],
         [30, 46, 63]],
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 63],
         [30, 46, 63],
         [30, 46, 63]],
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 62],
         [30, 46, 63],
         [30, 46, 63]]], dtype=uint8),
 None,
 None,
 None)

In [9]:
motors_dof = np.arange(7)
fingers_dof = np.arange(7,9)


panda.set_dofs_kp(
    np.array([4500, 4500, 3500, 3500, 2000, 2000, 2000, 100, 100]),
)
panda.set_dofs_kv(
    np.array([450, 450, 350, 350, 200, 200, 200, 10, 10]),
)
panda.set_dofs_force_range(
    np.array([-87, -87, -87, -87, -12, -12, -12, -100, -100]),
    np.array([87, 87, 87, 87, 12, 12, 12, 100, 100]),
)

# get the end-effector link
end_effector = panda.get_link('hand')

import time

# starting position
qpos = panda.inverse_kinematics(
    link = end_effector,
    pos = np.array([0.65, 0.5, 0.25]),
    quat = np.array([0, 1, 0, 0]),
)

In [10]:
scene.step()

[Genesis] [12:51:00] [INFO] Running at 2.16 FPS.


In [11]:
cam.render()

(array([[[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        [[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        [[90, 90, 90],
         [90, 90, 90],
         [90, 90, 90],
         ...,
         [41, 54, 69],
         [41, 54, 69],
         [41, 54, 69]],
 
        ...,
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 63],
         [30, 46, 63],
         [30, 46, 63]],
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 63],
         [30, 46, 63],
         [30, 46, 63]],
 
        [[40, 57, 75],
         [40, 57, 75],
         [40, 57, 75],
         ...,
         [30, 46, 62],
         [30, 46, 63],
         [30, 46, 63]]], dtype=uint8),
 None,
 None,
 None)

In [12]:
panda.control_dofs_position(qpos[:-2], motors_dof)
for i in range(100):
    scene.step()
    cam.render()

[Genesis] [12:51:03] [INFO] Running at 1.71 FPS.


[Genesis] [12:51:03] [INFO] Running at 1.80 FPS.
[Genesis] [12:51:03] [INFO] Running at 1.89 FPS.
[Genesis] [12:51:03] [INFO] Running at 1.98 FPS.
[Genesis] [12:51:03] [INFO] Running at 2.08 FPS.
[Genesis] [12:51:03] [INFO] Running at 2.19 FPS.
[Genesis] [12:51:03] [INFO] Running at 2.30 FPS.
[Genesis] [12:51:03] [INFO] Running at 2.41 FPS.
[Genesis] [12:51:03] [INFO] Running at 2.53 FPS.
[Genesis] [12:51:03] [INFO] Running at 2.66 FPS.
[Genesis] [12:51:03] [INFO] Running at 2.80 FPS.
[Genesis] [12:51:03] [INFO] Running at 2.94 FPS.
[Genesis] [12:51:03] [INFO] Running at 3.08 FPS.
[Genesis] [12:51:03] [INFO] Running at 3.24 FPS.
[Genesis] [12:51:03] [INFO] Running at 3.40 FPS.
[Genesis] [12:51:03] [INFO] Running at 3.57 FPS.
[Genesis] [12:51:03] [INFO] Running at 3.74 FPS.
[Genesis] [12:51:03] [INFO] Running at 3.93 FPS.
[Genesis] [12:51:03] [INFO] Running at 4.12 FPS.
[Genesis] [12:51:03] [INFO] Running at 4.31 FPS.
[Genesis] [12:51:03] [INFO] Running at 4.50 FPS.
[Genesis] [12:51:03]

In [28]:
cam.set_pose(pos=(0.75, -1.5, 1.0), lookat=(0.75, 0.5, 0.))

cam.render()

(array([[[46, 62, 80],
         [46, 62, 80],
         [46, 62, 80],
         ...,
         [60, 74, 92],
         [60, 75, 92],
         [60, 75, 92]],
 
        [[46, 62, 80],
         [46, 62, 80],
         [46, 62, 80],
         ...,
         [60, 74, 92],
         [60, 74, 92],
         [60, 75, 92]],
 
        [[46, 62, 80],
         [46, 62, 80],
         [46, 62, 80],
         ...,
         [59, 74, 92],
         [60, 74, 92],
         [60, 74, 92]],
 
        ...,
 
        [[31, 45, 60],
         [31, 45, 60],
         [31, 45, 60],
         ...,
         [32, 48, 65],
         [32, 48, 65],
         [32, 48, 65]],
 
        [[31, 45, 60],
         [31, 45, 60],
         [31, 45, 60],
         ...,
         [32, 48, 65],
         [32, 48, 65],
         [32, 48, 65]],
 
        [[31, 45, 60],
         [31, 45, 60],
         [31, 45, 60],
         ...,
         [32, 48, 65],
         [32, 48, 65],
         [32, 48, 65]]], dtype=uint8),
 None,
 None,
 None)